<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="34" started-at="2018-08-15T04:00:27Z" finished-at="2018-08-15T04:00:27Z">
    <groups>
    </groups>
    <test name="FlightSearch" duration-ms="34" started-at="2018-08-15T04:00:27Z" finished-at="2018-08-15T04:00:27Z">
      <class name="TestCases.SearchResultTests">
        <test-method status="PASS" signature="initializeTestBaseSetup(java.lang.reflect.Method)[pri:0, instance:TestCases.SearchResultTests@6500df86]" name="initializeTestBaseSetup" is-config="true" duration-ms="7" started-at="2018-08-15T09:30:27Z" finished-at="2018-08-15T09:30:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.SearchResultTests.VerifyCheapestPriceDisplayedOrNot()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTestBaseSetup -->
        <test-method status="FAIL" signature="VerifyCheapestPriceDisplayedOrNot()[pri:0, instance:TestCases.SearchResultTests@6500df86]" name="VerifyCheapestPriceDisplayedOrNot" duration-ms="7" started-at="2018-08-15T09:30:27Z" finished-at="2018-08-15T09:30:27Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at Utility.util.getTestData(util.java:147)
	at TestCases.SearchResultTests.VerifyCheapestPriceDisplayedOrNot(SearchResultTests.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyCheapestPriceDisplayedOrNot -->
        <test-method status="FAIL" signature="afterEachTestMethod(org.testng.ITestResult)[pri:0, instance:TestCases.SearchResultTests@6500df86]" name="afterEachTestMethod" is-config="true" duration-ms="0" started-at="2018-08-15T09:30:27Z" finished-at="2018-08-15T09:30:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyCheapestPriceDisplayedOrNot status=FAILURE method=SearchResultTests.VerifyCheapestPriceDisplayedOrNot()[pri:0, instance:TestCases.SearchResultTests@6500df86] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Utility.Base.afterEachTestMethod(Base.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterEachTestMethod -->
      </class> <!-- TestCases.SearchResultTests -->
      <class name="Utility.Base">
        <test-method status="PASS" signature="extentSetup(org.testng.ITestContext)[pri:0, instance:Utility.Base@553f17c]" name="extentSetup" is-config="true" duration-ms="300" started-at="2018-08-15T09:30:26Z" finished-at="2018-08-15T09:30:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@78e94dcf]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentSetup -->
        <test-method status="SKIP" signature="generateReport()[pri:0, instance:Utility.Base@553f17c]" name="generateReport" is-config="true" duration-ms="0" started-at="2018-08-15T09:30:27Z" finished-at="2018-08-15T09:30:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReport -->
      </class> <!-- Utility.Base -->
    </test> <!-- FlightSearch -->
  </suite> <!-- Suite1 -->
</testng-results>
